services:
  frontend:
    build:
      context: .
    command: ["npm", "run", "dev", "--legacy-peer-deps"]
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "4000:3000"
    restart: always
    networks:
      - pallet-optimization
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
networks:
  pallet-optimization:
    name: "pallet-optimization"
    external: true